'use strict';
(()=>{
const $=id=>document.getElementById(id),chips=['wildcard','free_hit','bench_boost','triple_captain'];let forecast,people;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tenths(x,name){if(!/^\d+(\.\d)?$/.test(String(x)))throw Error(name+': angiv et tal med højst én decimal');return Math.round(Number(x)*10)}
function validate(raw){
 if(!forecast)throw Error('Modeloutput ikke indlæst');
 if(raw.season!==forecast.season||raw.gw!==forecast.gws[0])throw Error('State og forecast skal have samme sæson/GW');
 if(!raw.source?.trim()||!Number.isFinite(Date.parse(raw.observed_at))||!/(Z|[+-]\d\d:\d\d)$/.test(raw.observed_at)||Date.parse(raw.observed_at)>Date.parse(forecast.data_asof))throw Error('Angiv et dokumenteret tidspunkt før forecast-cutoff');
 if(!Number.isInteger(raw.bank_tenths)||raw.bank_tenths<0||raw.bank_tenths>1000||!Number.isInteger(raw.free_transfers)||raw.free_transfers<1||raw.free_transfers>5)throw Error('Ugyldig bank/FT');
 if(raw.squad?.length!==15||new Set(raw.squad.map(p=>p.id)).size!==15)throw Error('Der kræves 15 forskellige spillere');
 const positions=[0,0,0,0,0],clubs={};
 for(const p of raw.squad){const player=people.get(p.id);if(!player||!Number.isInteger(p.purchase_price_tenths)||p.purchase_price_tenths<1||p.purchase_price_tenths>1000)throw Error('Spilleridentitet eller købspris mangler');positions[player.position]++;clubs[player.team_id]=(clubs[player.team_id]||0)+1}
 if(positions.slice(1).join(',')!=='2,5,5,3'||Object.values(clubs).some(n=>n>3))throw Error('Truppen skal have 2 GK, 5 DEF, 5 MID, 3 FWD og højst 3 fra samme klub');
 if(!raw.chips_used||Object.keys(raw.chips_used).sort().join(',')!==[...chips].sort().join(','))throw Error('Alle fire chiphistorikker kræves');
 for(const c of chips){const g=raw.chips_used[c];if(!Array.isArray(g)||new Set(g).size!==g.length||g.some(x=>!Number.isInteger(x)||x<1||x>=raw.gw))throw Error('Ugyldig chiphistorik: '+c)}
 return raw;
}
function form(){if(!$('confirmed').checked)throw Error('Bekræft købspriser og chiphistorik');return validate({season:forecast.season,gw:forecast.gws[0],source:$('source').value,observed_at:$('observed').value?$('observed').value+'Z':'',bank_tenths:tenths($('bank').value,'Bank'),free_transfers:Number($('ft').value),squad:[...$('squad').children].map((tr,i)=>({id:Number(tr.querySelector('select').value),purchase_price_tenths:tenths(tr.querySelector('input').value,'Købspris '+(i+1))})),chips_used:Object.fromEntries(chips.map(c=>[c,$(c).value.trim()?$(c).value.split(',').map(x=>Number(x.trim())):[]]))})}
function apply(raw){validate(raw);$('bank').value=(raw.bank_tenths/10).toFixed(1);$('ft').value=raw.free_transfers;$('source').value=raw.source;$('observed').value=new Date(raw.observed_at).toISOString().slice(0,19);[...$('squad').children].forEach((tr,i)=>{tr.querySelector('select').value=raw.squad[i].id;tr.querySelector('input').value=(raw.squad[i].purchase_price_tenths/10).toFixed(1)});chips.forEach(c=>$(c).value=raw.chips_used[c].join(','));$('confirmed').checked=false}
function message(s,error=false){$('message').textContent=s;$('message').className=error?'error':'good'}
$('save').onclick=()=>{try{const raw=form(),json=JSON.stringify(raw,null,2);localStorage.setItem('fpl-manager-state-v1',json);$('json').value=json;const url=URL.createObjectURL(new Blob([json+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='manager-state.json';a.click();URL.revokeObjectURL(url);message('Valideret. Ingen transfers er udført.')}catch(e){message(e.message,true)}};
$('importState').onchange=async e=>{try{apply(JSON.parse(await e.target.files[0].text()));message('State importeret; kontrollér og bekræft oplysningerne.')}catch(e){message(e.message,true)}};
$('importPlan').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.locked_model_active!==false||!p.ts_ran||p.forecast_cutoff!==forecast.data_asof||p.gw!==forecast.gws[0]||!Array.isArray(p.plan?.path))throw Error('Planen passer ikke til denne forecast eller har ugyldig status');const name=id=>people.get(id)?.name||id;$('plan').innerHTML='<h3>'+esc(p.ts_status)+' · GW '+p.gw+'</h3><p>Samlet vægtet planværdi: '+Number(p.plan.objective).toFixed(2)+'. Første handling er anbefalingen; senere handlinger er hypotetiske.</p><div class="scroll"><table><tr><th>GW</th><th>Ud</th><th>Ind</th><th>Hits</th><th>FT efter</th><th>Hold-xP</th></tr>'+p.plan.path.map(a=>'<tr><td>'+a.gw+'</td><td>'+a.outgoing.map(id=>esc(name(id))).join(', ')+'</td><td>'+a.incoming.map(id=>esc(name(id))).join(', ')+'</td><td>'+a.official_hit_points+'</td><td>'+a.free_transfers_after+'</td><td>'+Number(a.projected_manager_score).toFixed(2)+'</td></tr>').join('')+'</table></div><h3>Start-XI, kaptajn og bænk</h3><p>'+p.lineup.map(r=>esc(r.role)+': '+esc(name(r.id))).join(' · ')+'</p><h3>Chips: '+esc(p.chips_status)+'</h3>'+(p.chip_assessment?'<p>Foreløbigt valg uden manglende TC-scenarier: '+esc(p.chip_assessment.provisional_choice_without_missing_tc)+' · FH-gevinst '+esc(p.chip_assessment.fh_gain)+' · WC-gevinst '+esc(p.chip_assessment.wc_gain)+' · BB-gevinst '+esc(p.chip_assessment.bb_gain)+'</p>':'')+'<p>Fremtidig chip-GW og fuld TC-afgørelse: Not Available.</p><ul>'+p.blockers.map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul>';message('Originalt beregnet output importeret. Status forbliver diagnostisk.')}catch(e){message(e.message,true)}};
fetch('vfinal-diagnostic.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Forecast mangler');return r.json()}).then(d=>{if(d.model!=='original_locked_vFinal_diagnostic'||d.locked_model_active!==false)throw Error('Ugyldig forecast-kontrakt');forecast=d;people=new Map(d.players.map(p=>[p.id,p]));$('forecast').textContent='Forecast: '+d.season+' GW '+d.gws.join('–')+' · cutoff '+d.data_asof+' · diagnostiske original-vFinal-xP';const options='<option value="">Vælg spiller</option>'+[...d.players].sort((a,b)=>a.name.localeCompare(b.name,'da')).map(p=>'<option value="'+p.id+'">'+esc(p.name)+' · '+esc(p.team)+' · '+['','GK','DEF','MID','FWD'][p.position]+'</option>').join('');$('squad').innerHTML=Array.from({length:15},(_,i)=>'<tr><td>'+(i+1)+'</td><td><select>'+options+'</select></td><td><input type="number" min="0.1" step="0.1" aria-label="Faktisk købspris '+(i+1)+'"></td></tr>').join('');$('chips').innerHTML=chips.map(c=>'<label>'+c+'<br><input id="'+c+'" placeholder="Fx 3, 22"></label>').join('');const saved=localStorage.getItem('fpl-manager-state-v1');if(saved){try{apply(JSON.parse(saved))}catch(e){message('Tidligere state passer ikke til forecast. Importér eller opdatér det.',true)}}else{try{const squad=JSON.parse(localStorage.getItem('fpl-current-squad-v1')||'null');if(squad?.season===d.season&&squad.ids?.length===15)[...$('squad').children].forEach((tr,i)=>tr.querySelector('select').value=squad.ids[i])}catch(e){}}}).catch(e=>message('Not Available: '+e.message,true));
})();
