'use strict';
(()=>{
const $=id=>document.getElementById(id),chips=['wildcard','free_hit','bench_boost','triple_captain'];let forecast,people,usable=false,officialData;
const ordered=x=>Array.isArray(x)?x.map(ordered):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,ordered(x[k])])):x;
async function stateHash(raw){const bytes=new TextEncoder().encode(JSON.stringify(ordered(raw)));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tenths(x,name){if(!/^\d+(\.\d)?$/.test(String(x)))throw Error(name+': angiv et tal med højst én decimal');return Math.round(Number(x)*10)}
function validate(raw){
 if(forecast)usable=FplForecastWindow.check(forecast,officialData).usable;
 if(!forecast)throw Error('Modeloutput ikke indlæst');
 if(!usable)throw Error('Not Available: forecast er udløbet eller matcher ikke den officielle næste GW');
 if(raw.season!==forecast.season||raw.gw!==forecast.gws[0])throw Error('State og forecast skal have samme sæson/GW');
 if(!raw.source?.trim()||!Number.isFinite(Date.parse(raw.observed_at))||!/(Z|[+-]\d\d:\d\d)$/.test(raw.observed_at)||Date.parse(raw.observed_at)>Date.parse(forecast.data_asof))throw Error('Angiv et dokumenteret tidspunkt før forecast-cutoff');
 if(!Number.isInteger(raw.bank_tenths)||raw.bank_tenths<0||raw.bank_tenths>1000||!Number.isInteger(raw.free_transfers)||raw.free_transfers<0||raw.free_transfers>5)throw Error('Ugyldig bank/FT');
 if(raw.squad?.length!==15||new Set(raw.squad.map(p=>p.id)).size!==15)throw Error('Der kræves 15 forskellige spillere');
 const positions=[0,0,0,0,0],clubs={};
 for(const p of raw.squad){const player=people.get(p.id);if(!player||!Number.isInteger(p.purchase_price_tenths)||p.purchase_price_tenths<1||p.purchase_price_tenths>1000)throw Error('Spilleridentitet eller købspris mangler');positions[player.position]++;clubs[player.team_id]=(clubs[player.team_id]||0)+1}
 if(positions.slice(1).join(',')!=='2,5,5,3'||Object.values(clubs).some(n=>n>3))throw Error('Truppen skal have 2 GK, 5 DEF, 5 MID, 3 FWD og højst 3 fra samme klub');
 if(!raw.chips_used||Object.keys(raw.chips_used).sort().join(',')!==[...chips].sort().join(','))throw Error('Alle fire chiphistorikker kræves');
 for(const c of chips){const g=raw.chips_used[c];if(!Array.isArray(g)||new Set(g).size!==g.length||g.some(x=>!Number.isInteger(x)||x<1||x>=raw.gw)||g.filter(x=>x<=19).length>1||g.filter(x=>x>=20).length>1)throw Error('Ugyldig chiphistorik: '+c)}
 return raw;
}
function form(){if(!$('confirmed').checked)throw Error('Bekræft købspriser og chiphistorik');return validate({season:forecast.season,gw:Number($('gw').value),source:$('source').value,observed_at:$('observed').value?$('observed').value+'Z':'',bank_tenths:tenths($('bank').value,'Bank'),free_transfers:Number($('ft').value),squad:[...$('squad').children].map((tr,i)=>({id:Number(tr.querySelector('select').value),purchase_price_tenths:tenths(tr.querySelector('input').value,'Købspris '+(i+1))})),chips_used:Object.fromEntries(chips.map(c=>[c,$(c).value.trim()?$(c).value.split(',').map(x=>Number(x.trim())):[]]))})}
function apply(raw){validate(raw);$('gw').value=raw.gw;$('bank').value=(raw.bank_tenths/10).toFixed(1);$('ft').value=raw.free_transfers;$('source').value=raw.source;$('observed').value=new Date(raw.observed_at).toISOString().slice(0,19);[...$('squad').children].forEach((tr,i)=>{tr.querySelector('select').value=raw.squad[i].id;tr.querySelector('input').value=(raw.squad[i].purchase_price_tenths/10).toFixed(1)});chips.forEach(c=>$(c).value=raw.chips_used[c].join(','));$('confirmed').checked=false}
function message(s,error=false){$('message').textContent=s;$('message').className=error?'error':'good'}
$('save').onclick=()=>{try{const raw=form(),json=JSON.stringify(raw,null,2);localStorage.setItem('fpl-manager-state-v1',json);$('json').value=json;const url=URL.createObjectURL(new Blob([json+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='manager-state.json';a.click();URL.revokeObjectURL(url);message('Valideret. Ingen transfers er udført.')}catch(e){message(e.message,true)}};
$('importState').onchange=async e=>{try{apply(JSON.parse(await e.target.files[0].text()));message('State importeret; kontrollér og bekræft oplysningerne.')}catch(e){message(e.message,true)}};
$('importPlan').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());const stored=localStorage.getItem('fpl-manager-state-v1');if(!stored||p.manager_state_sha256!==await stateHash(validate(JSON.parse(stored))))throw Error('Planen tilhører ikke dit validerede manager-state. Eksportér dit state før beregningen.');if(p.locked_model_active!==false||!p.ts_ran||p.forecast_cutoff!==forecast.data_asof||p.gw!==forecast.gws[0]||!Array.isArray(p.plan?.path))throw Error('Planen passer ikke til denne forecast eller har ugyldig status');if(p.plan.path.length!==6||!Number.isFinite(p.plan.objective)||p.plan.path.some((a,i)=>a.gw!==forecast.gws[i]||!Number.isInteger(a.free_transfers_after)||a.free_transfers_after<1||a.free_transfers_after>5||!Number.isInteger(a.official_hit_points)||a.official_hit_points<0||a.official_hit_points%4!==0||!Number.isFinite(a.projected_manager_score)||![a.outgoing,a.incoming].every(ids=>Array.isArray(ids)&&ids.every(id=>Number.isInteger(id)&&people.has(id))))||!Array.isArray(p.lineup)||p.lineup.length!==15||!Array.isArray(p.blockers))throw Error('Ugyldige beregnede planfelter');localStorage.setItem('fpl-manager-plan-v1',JSON.stringify(p));FplPlanView.render(p,people,$('plan'));message('Originalt beregnet output importeret. Status forbliver diagnostisk.')}catch(e){message(e.message,true)}};
Promise.all([fetch('vfinal-diagnostic.json',{cache:'no-store'}),fetch('current-players.json',{cache:'no-store'})]).then(async rs=>{if(rs.some(r=>!r.ok))throw Error('Forecast eller officiel GW mangler');return Promise.all(rs.map(r=>r.json()))}).then(([d,official])=>{officialData=official;const status=FplForecastWindow.check(d,official);usable=status.usable;$('forecast').textContent=status.reason;return d}).then(async d=>{if(d.model!=='original_locked_vFinal_diagnostic'||d.locked_model_active!==false)throw Error('Ugyldig forecast-kontrakt');forecast=d;$('gw').value=d.gws[0];people=new Map(d.players.map(p=>[p.id,p]));$('forecast').textContent+=' · Forecast: '+d.season+' GW '+d.gws.join('–')+' · cutoff '+d.data_asof+' · diagnostiske original-vFinal-xP';const options='<option value="">Vælg spiller</option>'+[...d.players].sort((a,b)=>a.name.localeCompare(b.name,'da')).map(p=>'<option value="'+p.id+'">'+esc(p.name)+' · '+esc(p.team)+' · '+['','GK','DEF','MID','FWD'][p.position]+'</option>').join('');$('squad').innerHTML=Array.from({length:15},(_,i)=>'<tr><td>'+(i+1)+'</td><td><select aria-label="Spiller '+(i+1)+'">'+options+'</select></td><td><input type="number" min="0.1" step="0.1" aria-label="Faktisk købspris '+(i+1)+'"></td></tr>').join('');$('chips').innerHTML=chips.map(c=>'<label>'+c+'<br><input id="'+c+'" placeholder="Fx 3, 22"></label>').join('');const saved=localStorage.getItem('fpl-manager-state-v1');if(saved){try{apply(JSON.parse(saved))}catch(e){message('Tidligere state passer ikke til forecast. Importér eller opdatér det.',true)}}else{try{const squad=JSON.parse(localStorage.getItem('fpl-current-squad-v1')||'null');if(squad?.season===d.season&&squad.ids?.length===15)[...$('squad').children].forEach((tr,i)=>tr.querySelector('select').value=squad.ids[i])}catch(e){}}const plan=localStorage.getItem('fpl-manager-plan-v1');if(plan&&saved&&usable){try{const p=JSON.parse(plan);if(p.forecast_cutoff===d.data_asof&&p.manager_state_sha256===await stateHash(validate(JSON.parse(saved))))FplPlanView.render(p,people,$('plan'))}catch(e){message('Gemt plan er ikke længere tilgængelig: '+e.message,true)}}}).catch(e=>message('Not Available: '+e.message,true));
})();

