'use strict';
window.FplPlanView={render(p,people,target){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const name=id=>esc(people.get(Number(id))?.name||id),num=x=>Number.isFinite(x)?Number(x).toFixed(2):'Not Available';
 const c=p.comparison,a=p.chip_assessment,first=p.plan.path[0],tc=a?.tc;
 const lineup=p.lineup.map(r=>'<tr><td>'+esc(r.role)+'</td><td>'+name(r.id)+'</td><td>'+esc(r.position)+'</td><td>'+num(r.xpts_mean)+'</td></tr>').join('');
 const actions=p.plan.path.map(r=>'<tr><td>'+r.gw+'</td><td>'+r.outgoing.map(name).join(', ')+'</td><td>'+r.incoming.map(name).join(', ')+'</td><td>'+r.official_hit_points+'</td><td>'+num(r.uncertainty_penalty)+'</td><td>'+r.free_transfers_after+'</td><td>£'+(r.bank_after/10).toFixed(1)+'</td><td>'+num(r.projected_manager_score)+'</td></tr>').join('');
 const chipRows=a?[['Free Hit',a.fh_gain,a.q_fh],['Wildcard',a.wc_gain,a.q_wc],['Bench Boost',a.bb_gain,a.q_bb]].map(([n,g,q])=>'<tr><td>'+n+'</td><td>'+num(g)+'</td><td>'+num(q)+'</td><td>GW '+p.gw+' · diagnostisk vurdering</td></tr>').join(''):'';
 const tcText=tc?'<p><strong>TC er manuelt:</strong> '+esc(tc.action)+' · ekstra TC-point nu '+num(tc.use_now_value)+' · gemmeværdi '+num(tc.save_option_value)+'.</p><p>Bedste konkrete fremtidige mulighed: GW '+esc(tc.best_future_gw)+' · '+esc(tc.best_future_candidate_name)+'. Den anonyme DGW-mulighed kan være bedre; den angiver ingen bestemt spiller eller GW. Modellen replanner ved næste deadline.</p>':'<p>Triple Captain: Not Available – verificerede scenarier mangler.</p>';
 target.innerHTML=(p.validation_only?'<div class="notice">KUN VALIDERING: Dette er et beregnet testhold, ikke dit FPL-hold.</div>':'')+'<h2>'+esc(p.ts_status)+' · GW '+p.gw+'</h2><p>Forecast-cutoff: '+esc(p.forecast_cutoff)+'. Ingen officielle transfers eller chips er udført.</p><nav><a href="#teamResult">My Team</a> · <a href="#transferResult">Transfers</a> · <a href="#chipResult">Chips</a> · <a href="vfinal-diagnostic.html">Spillerforecast</a> · <a href="models.html">Matematik</a></nav><section id="teamResult"><h3>Start-XI, kaptajn og bænk</h3><div class="scroll"><table><tr><th>Rolle</th><th>Spiller</th><th>Position</th><th>GW-xP</th></tr>'+lineup+'</table></div></section><section id="transferResult"><h3>Transfers og begrundelse</h3><p>'+esc(p.reason||p.interpretation)+'</p>'+(c?'<p>Vægtet gevinst mod samme trup uden transfers: <strong>'+num(c.plan_gain_over_hold)+'</strong>. Første GW: '+num(c.current_gw_gain_before_hits)+' point før '+c.current_gw_official_hit_points+' officielle hit-point. Fremtidig bank og FT indgår i den originale planner.</p>':'')+'<div class="scroll"><table><tr><th>GW</th><th>Ud</th><th>Ind</th><th>Hit-point</th><th>Usikkerhedsbuffer</th><th>FT efter</th><th>Bank efter</th><th>XI + kaptajn xP</th></tr>'+actions+'</table></div><p>Kun GW '+first.gw+' er den aktuelle anbefaling. Senere handlinger er en hypotetisk plan fra samme cutoff og skal genberegnes.</p></section><section id="chipResult"><h3>Chips · '+esc(p.chips_status)+'</h3>'+(a?'<p>Koordinatorens foreløbige aktuelle valg: <strong>'+esc(a.provisional_choice_without_missing_tc)+'</strong>. Positive nettoværdier kan passere de låste chipgrænser; ved lige værdier beholdes chippen.</p><div class="scroll"><table><tr><th>Chip</th><th>Forventet gevinst</th><th>Gevinst minus låst tærskel</th><th>Vurdering</th></tr>'+chipRows+'</table></div>'+tcText+'<p>Fuld samlet fremtidig chipplan: Not Available. Ovenstående er aktuelle chipvalg og TC-optioner, ikke en verificeret kalender for alle fire chips.</p>':'<p>Not Available. '+esc(p.chip_error?.message||'Intet verificeret chipoutput')+'</p>')+'</section><details><summary>Datamangler og status</summary><ul>'+(p.blockers||[]).map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul></details>';
}};
